#!/usr/bin/env node
/**
 * generate-fixture.js
 *
 * Generates a real Besu QBFT bundle-proof fixture for QBFTVerifier.verifyBundle,
 * sourced from a deployed `ClprService` with a populated `Channel` (via
 * `tools/qbft-proof-generator/QbftFixtureSetup.s.sol`).
 *
 * Steps:
 *   1. Start a 3-validator QBFT Besu cluster via docker-compose in this directory.
 *      All three nodes form a consensus quorum so each block carries ≥ 2 committed
 *      seals (2f+1 for f=1).
 *   2. Run `forge script QbftFixtureSetup.s.sol --broadcast` to deploy the full
 *      `ClprService` dependency graph, configure it, and walk a channel through
 *      `registerChannel` + `completeChannel`. Parse stdout for the deployed
 *      service address, the populated channelId, and supporting addresses.
 *   3. Derive the 4 storage trie keys this verifier expects from the populated
 *      channel's struct slots (per `_channels[id]` storage layout at root
 *      slot 17): struct offsets {+1, +2, +4, +5} above
 *      `keccak256(abi.encode(channelId, 17))`.
 *   4. Call `eth_getProof` for those 4 keys, fetch `debug_getRawHeader`, and pack
 *      everything into the 5-item RLP payload QBFTVerifier expects.
 *   5. Write fixture files into `test/verifiers/qbft/fixtures/`.
 *   6. Tear down the Besu cluster.
 *
 * Prerequisites: Docker, Node.js 22+, Foundry (forge, cast).
 * Usage: node generate-fixture.js
 */

import { RLP } from "@ethereumjs/rlp";
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, "..", "..");
const FIXTURES_DIR = join(PROJECT_ROOT, "test", "verifiers", "qbft", "fixtures");

const RPC = "http://127.0.0.1:18545";

// Anvil account 0 — funded in the Besu QBFT genesis; also serves as the validator
const DEPLOYER_PRIVATE_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
const VALIDATOR_ADDRESS = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266";

// `_channels` lives at root slot 17 of `ClprService`. Authoritative source:
// storage-layout.json (regenerated by `forge build`).
const CHANNELS_SLOT = 17;

// `_messageQueues` lives at root slot 1. Within MessageValue, runningHashAfterProcessing
// is at struct offset +1 (payload is offset 0).
const MESSAGE_QUEUES_SLOT = 1;
const MESSAGE_RUNNING_HASH_OFFSET = 1n;

// `Channel` struct offsets that QBFTVerifier reads. The storage proof MUST lead with struct
// slot+0 (the channelId itself): QBFTVerifier bootstraps the channelId from entries[0] via a
// self-anchor check (slotNumber == keccak256(abi.encode(value, 17))), then derives slots +1/+2/+4/+5
// from it and looks them up by key. Order after slot+0 is not significant (lookup-by-key), but
// slot+0 must be first.
//   entries[0] → struct slot+0: channelId (self-anchoring bootstrap entry)
//   entries[1] → struct slot+1: verifier|status|nextMessageId (packed)
//   entries[2] → struct slot+2: ackedMessageId|receivedMessageId|nextExpectedReplyId (packed)
//   entries[3] → struct slot+4: sentRunningHash
//   entries[4] → struct slot+5: receivedRunningHash
//   entries[5] → lastMessage.runningHashAfterProcessing (_messageQueues mapping; only with messages)
const PROVEN_STRUCT_OFFSETS = [0n, 1n, 2n, 4n, 5n];

// ─────────────────────────────────────────────────────────────────────────────
// RLP encoding (via @ethereumjs/rlp — aligned with generate-configproof.js)
// ─────────────────────────────────────────────────────────────────────────────

/// RLP-encode a (possibly nested) structure of byte buffers and lists.
function rlpEncode(input) {
  return Buffer.from(RLP.encode(input));
}

/// Decode an already-encoded RLP byte string so it can be spliced into a larger list
/// as a nested list (rather than re-wrapped as a byte string).
function rlpDecode(input) {
  return RLP.decode(input);
}

function castKeccak(hexInput) {
  const out = execSync(`cast keccak ${hexInput}`, { encoding: "utf-8" }).trim();
  return out.startsWith("0x") ? out.slice(2) : out;
}

// Derive the storage slot for _messageQueues[channelId][messageId].runningHashAfterProcessing.
// outer = keccak256(abi.encode(channelId, MESSAGE_QUEUES_SLOT))
// inner = keccak256(abi.encode(messageId, outer))
// slot  = inner + MESSAGE_RUNNING_HASH_OFFSET
function deriveMessageRunningHashSlot(channelIdHex, messageId) {
  const idHex = channelIdHex.startsWith("0x") ? channelIdHex.slice(2) : channelIdHex;
  const mqSlotHex = BigInt(MESSAGE_QUEUES_SLOT).toString(16).padStart(64, "0");
  const outer = BigInt("0x" + castKeccak("0x" + idHex + mqSlotHex));
  const msgIdHex = messageId.toString(16).padStart(64, "0");
  const outerHex = outer.toString(16).padStart(64, "0");
  const inner = BigInt("0x" + castKeccak("0x" + msgIdHex + outerHex));
  const slot = (inner + MESSAGE_RUNNING_HASH_OFFSET) & ((1n << 256n) - 1n);
  return "0x" + slot.toString(16).padStart(64, "0");
}

function deriveSlotKey(channelIdHex, structOffset) {
  const idHex = channelIdHex.startsWith("0x") ? channelIdHex.slice(2) : channelIdHex;
  if (idHex.length !== 64) throw new Error(`channelId must be 32 bytes (64 hex), got ${idHex.length}`);

  // abi.encode(bytes32, uint256) = 64 bytes (each left-padded).
  const slotHex = BigInt(CHANNELS_SLOT).toString(16).padStart(64, "0");
  const baseSlot = castKeccak("0x" + idHex + slotHex);

  // structSlot = baseSlot + structOffset (mod 2^256, but offsets are tiny here).
  const structSlotBig = (BigInt("0x" + baseSlot) + structOffset) & ((1n << 256n) - 1n);
  return "0x" + structSlotBig.toString(16).padStart(64, "0");
}

// ─────────────────────────────────────────────────────────────────────────────
// JSON-RPC helper
// ─────────────────────────────────────────────────────────────────────────────

let rpcId = 0;
async function rpc(method, params = []) {
  const body = JSON.stringify({ jsonrpc: "2.0", method, params, id: ++rpcId });
  const res = await fetch(RPC, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body,
  });
  const json = await res.json();
  if (json.error) throw new Error(`RPC ${method}: ${JSON.stringify(json.error)}`);
  return json.result;
}

async function waitForRpc(maxWait = 60_000) {
  const start = Date.now();
  while (Date.now() - start < maxWait) {
    try {
      await rpc("eth_chainId");
      return;
    } catch {
      await new Promise((r) => setTimeout(r, 500));
    }
  }
  throw new Error("Besu RPC not ready after " + maxWait + "ms");
}

function shell(cmd, opts = {}) {
  return execSync(cmd, { encoding: "utf-8", ...opts }).trim();
}

// ─────────────────────────────────────────────────────────────────────────────
// Bootstrap configProof generation
// ─────────────────────────────────────────────────────────────────────────────

// Mirror the throttle values hardcoded in generate-configproof.js so the
// bootstrap configProof and the final one agree on throttle parameters.
const BOOTSTRAP_THROTTLES = [100n, 100_000n, 1_000_000n, 1_000n, 100_000n];
// Must match the QBFT epochlength in genesis.json.
const EPOCH_LENGTH = 30_000n;

// Build a minimal configProof that QBFTVerifier.verifyConfig will accept, using
// `headerRlpBuf` as the block header (field 8).  Service address and codeHash are
// zeros because they are not known yet; generate-configproof.js overwrites this
// file after the bundle fixtures have been written with the real values.
function buildBootstrapConfigProof(headerRlpBuf) {
  const validatorAddrBuf = hexToBuf(VALIDATOR_ADDRESS);
  const serviceAddr = Buffer.alloc(20, 0);
  const codeHash = Buffer.alloc(32, 0);

  const bootstrapTrustAnchorRlp = rlpEncode([validatorAddrBuf, serviceAddr, codeHash]);

  return rlpEncode([
    validatorAddrBuf,                        // 0 validatorAddr
    serviceAddr,                             // 1 serviceAddr (zeros — placeholder)
    codeHash,                                // 2 codeHash (zeros — placeholder)
    Buffer.from("eip155:1"),                 // 3 chainId
    Buffer.alloc(0),                         // 4 peerConfigNanos (empty)
    BOOTSTRAP_THROTTLES.map((v) => hexToTrimmedBuf("0x" + v.toString(16))), // 5 throttles
    bootstrapTrustAnchorRlp,                 // 6 trustAnchor (doubly-encoded: byte-string wrapping an RLP list)
    Buffer.alloc(0),                         // 7 trustAnchorId (empty)
    rlpDecode(headerRlpBuf),                 // 8 blockHeader (raw RLP list spliced as a nested list)
    hexToTrimmedBuf("0x" + EPOCH_LENGTH.toString(16)), // 9 epochLength
  ]);
}

async function writeBootstrapConfigProof() {
  console.log("Bootstrap: writing configProof.hex from current block so the Forge script can proceed...");
  // Wait for at least one QBFT block so the header carries committed seals.
  let blockNum = await rpc("eth_blockNumber");
  while (BigInt(blockNum) === 0n) {
    await new Promise((r) => setTimeout(r, 500));
    blockNum = await rpc("eth_blockNumber");
  }
  const rawHeaderHex = await rpc("debug_getRawHeader", [blockNum]);
  const headerRlp = hexToBuf(rawHeaderHex);
  const configProof = buildBootstrapConfigProof(headerRlp);
  writeFileSync(join(FIXTURES_DIR, "configProof.hex"), configProof.toString("hex") + "\n");
  console.log(`   Written bootstrap configProof.hex (${configProof.length} bytes, block ${blockNum})\n`);
}

// ─────────────────────────────────────────────────────────────────────────────
// Bundle content protobuf
// ─────────────────────────────────────────────────────────────────────────────

// `ClprBundleContent`: field 2 (LEN) = repeated ClprMessagePayload. Inner = the
// raw payload bytes; the wire-level wrap is `0x12 <varint length> <payload>`.
// Bundle content is built dynamically from the real message emitted by the Forge
// script after sendMessage is called.  See buildBundleContent() below.

// ─────────────────────────────────────────────────────────────────────────────
// Hex helpers
// ─────────────────────────────────────────────────────────────────────────────

function hexToBuf(hex) {
  if (!hex) return Buffer.alloc(0);
  const h = hex.startsWith("0x") ? hex.slice(2) : hex;
  if (h.length === 0) return Buffer.alloc(0);
  return Buffer.from(h.length % 2 ? "0" + h : h, "hex");
}

function hexToTrimmedBuf(hex) {
  if (!hex || hex === "0x0" || hex === "0x") return Buffer.alloc(0);
  let h = hex.startsWith("0x") ? hex.slice(2) : hex;
  h = h.replace(/^0+/, "");
  if (h.length === 0) return Buffer.alloc(0);
  if (h.length % 2) h = "0" + h;
  return Buffer.from(h, "hex");
}

// ─────────────────────────────────────────────────────────────────────────────
// Forge script invocation + stdout parsing
// ─────────────────────────────────────────────────────────────────────────────

function runFixtureSetupScript() {
  console.log("   forge script: deploying ClprService + completing channel...");
  const cmd = [
    "forge", "script",
    "tools/qbft-proof-generator/QbftFixtureSetup.s.sol:QbftFixtureSetup",
    "--rpc-url", RPC,
    "--broadcast",
    "--slow", // serialize tx submission — Besu's tx pool is fussy under load
    "--via-ir",
    "-vvv",
  ].join(" ");

  const stdout = shell(cmd, {
    cwd: PROJECT_ROOT,
    env: { ...process.env, PRIVATE_KEY: DEPLOYER_PRIVATE_KEY },
    maxBuffer: 64 * 1024 * 1024,
  });

  // Pull the FIXTURE_OUT::KEY lines out of the script log. forge prefixes each
  // line with whitespace inside the "== Logs ==" section.
  const out = {};
  for (const line of stdout.split("\n")) {
    const m = line.match(/FIXTURE_OUT::([A-Z_0-9]+)\s+(.+?)\s*$/);
    if (m) out[m[1]] = m[2].trim();
  }
  for (const k of ["CLPR_SERVICE", "QBFT_VERIFIER", "CHANNEL_ID", "PEER_SIGNER", "DEPLOYER", "VALIDATOR", "MSG1_PAYLOAD"]) {
    if (!out[k]) {
      console.error("forge script stdout follows:\n" + stdout);
      throw new Error(`forge script did not emit FIXTURE_OUT::${k}`);
    }
  }
  // CHANNEL_ID is logged as a uint256 (decimal). Normalise to a 32-byte hex.
  const channelIdBig = BigInt(out.CHANNEL_ID);
  out.CHANNEL_ID = "0x" + channelIdBig.toString(16).padStart(64, "0");
  return out;
}

// ─────────────────────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────────────────────

async function main() {
  console.log("=== Besu QBFT Fixture Generator ===\n");

  // 1. Start Besu cluster.
  console.log("1. Starting Besu QBFT cluster...");
  try { execSync("docker compose down -v 2>/dev/null || true", { cwd: __dirname, stdio: "pipe" }); } catch { }
  execSync("docker compose up -d", { cwd: __dirname, stdio: "inherit" });

  try {
    await waitForRpc(60_000);
    console.log("   Besu is ready.\n");

    // 1b. Bootstrap: write a valid configProof.hex before the Forge script needs it.
    //     The file is overwritten by generate-configproof.js afterwards with the real
    //     service address and codeHash from the bundle fixtures.
    await writeBootstrapConfigProof();

    // 2. Deploy ClprService + complete a channel via the Foundry script.
    console.log("2. Provisioning ClprService and a completed Channel...");
    const provisioned = runFixtureSetupScript();
    const contractAddress = provisioned.CLPR_SERVICE.toLowerCase();
    const verifierAddr = provisioned.QBFT_VERIFIER.toLowerCase();
    const channelId = provisioned.CHANNEL_ID.toLowerCase();
    const validator = provisioned.VALIDATOR.toLowerCase();
    console.log(`   ClprService:     ${contractAddress}`);
    console.log(`   QBFTVerifier:    ${verifierAddr}`);
    console.log(`   ChannelId:    ${channelId}`);
    console.log(`   Validator:       ${validator}\n`);

    // 3. Derive storage trie keys:
    //    entries 0-4 = Channel struct offsets +0, +1, +2, +4, +5 (slot+0 = channelId, first)
    //    entry  5    = lastMessage.runningHashAfterProcessing (messageId = nextMessageId - 1)
    console.log("3. Deriving storage-slot indices for the proven fields...");
    // After sendMessage, nextMessageId == 2, so lastMessageId == 1.
    const lastMessageId = 1n;
    const msgRunningHashSlot = deriveMessageRunningHashSlot(channelId, lastMessageId);
    console.log(`   lastMessage(id=${lastMessageId}) runningHashAfterProcessing → ${msgRunningHashSlot}`);
    const channelSlots = PROVEN_STRUCT_OFFSETS.map((off) => deriveSlotKey(channelId, off));
    for (let i = 0; i < channelSlots.length; i++) {
      console.log(`   struct slot+${PROVEN_STRUCT_OFFSETS[i]} → storage index ${channelSlots[i]}`);
    }
    const storageKeys = [...channelSlots, msgRunningHashSlot];
    console.log();

    // 4. Fetch eth_getProof.
    console.log("4. Fetching eth_getProof...");
    let proofBlock = await rpc("eth_blockNumber");
    let proof = await rpc("eth_getProof", [contractAddress, storageKeys, proofBlock]);
    console.log(`   Account proof nodes: ${proof.accountProof.length}`);
    console.log(`   Storage proofs:      ${proof.storageProof.length}`);
    for (let i = 0; i < proof.storageProof.length; i++) {
      console.log(`     [${i}] key=${proof.storageProof[i].key} value=${proof.storageProof[i].value} proofNodes=${proof.storageProof[i].proof.length}`);
    }
    console.log(`   Storage root: ${proof.storageHash}`);
    console.log(`   Code hash:    ${proof.codeHash}\n`);

    // 4a. QBFTVerifier.verifyBundle checks codeHash of the contract at the service address
    //     from the trust anchor. The service address = QBFTVerifier address (from verifyConfig).
    //     So the trust anchor codeHash must match the QBFTVerifier's actual codeHash.
    //     Also need QBFTVerifier's account proof (in payload[2] of the RLP).
    console.log("4a. Fetching QBFTVerifier codeHash and account proof...");
    const qbftProof = await rpc("eth_getProof", [verifierAddr, [], proofBlock]);
    const qbftCodeHash = qbftProof.codeHash;
    console.log(`   QBFTVerifier codeHash: ${qbftCodeHash}\n`);

    // 5. Fetch raw header.
    console.log("5. Fetching block header...");
    let rawHeaderHex;
    try {
      rawHeaderHex = await rpc("debug_getRawHeader", [proofBlock]);
      console.log(`   debug_getRawHeader OK (${(rawHeaderHex.length - 2) / 2} bytes)`);
    } catch (e) {
      console.log("   debug_getRawHeader failed: " + e.message);
      console.log("   Falling back to JSON-built header (WARNING: may lack QBFT committed seals!)");
      rawHeaderHex = null;
    }

    const block = await rpc("eth_getBlockByNumber", [proofBlock, false]);
    console.log(`   Block hash:  ${block.hash}`);
    console.log(`   State root:  ${block.stateRoot}`);

    const headerRlp = rawHeaderHex ? hexToBuf(rawHeaderHex) : buildHeaderRlpFromBlock(block);
    console.log(`   Header RLP:  ${headerRlp.length} bytes\n`);

    // 6. Build 4-item RLP payload (aligned with BesuQbftProofVerifier from clpr-hiero).
    console.log("6. Building RLP payload...");

    // [1] accountProof = [node0, node1, ...]
    const accountProof = proof.accountProof.map((h) => hexToBuf(h));

    // [2] storageProof = [ [key, [proofNode0, ...]], ... ]
    // No value field: ClprEvmStateProof.verifyProvenSlots reads each slot's value
    // from the Merkle proof leaf, so carrying it here would be redundant data.
    const storageProof = proof.storageProof.map((sp) => [
      hexToBuf(sp.key),
      sp.proof.map((h) => hexToBuf(h)),
    ]);

    // [3] bundleContent protobuf
    const msg1PayloadBuf = hexToBuf(provisioned.MSG1_PAYLOAD);
    const BUNDLE_CONTENT_BYTES = Buffer.concat([
      Buffer.from([0x12, msg1PayloadBuf.length]),
      msg1PayloadBuf,
    ]);

    // Top-level 5-item list: [currentHeader, epochHeaders[], accountProof, storageProof, bundleContent]
    const topLevelPayload = rlpEncode([
      rlpDecode(headerRlp), // 0: current block header (raw RLP list spliced as a nested list)
      [],                   // 1: epoch headers (empty — no validator rotation in this block)
      accountProof,         // 2: account proof
      storageProof,         // 3: storage proof
      BUNDLE_CONTENT_BYTES, // 4: bundle content
    ]);

    console.log(`   Total payload: ${topLevelPayload.length} bytes\n`);

    // 7. Write outputs.
    console.log("7. Writing fixture files...");
    writeFileSync(join(FIXTURES_DIR, "bundlePayload.hex"), topLevelPayload.toString("hex") + "\n");
    console.log("   Written bundlePayload.hex");

    const trustAnchorRlp = rlpEncode([
      hexToBuf(VALIDATOR_ADDRESS),
      hexToBuf(contractAddress),
      hexToBuf(proof.codeHash),
    ]);
    writeFileSync(join(FIXTURES_DIR, "trustAnchor.hex"), trustAnchorRlp.toString("hex") + "\n");
    console.log("   Written trustAnchor.hex");

    // ChannelContext: channelId (32 bytes) || remoteServiceAddress (20 bytes), matching
    // ClprTypes.encodeChannelContext.
    const channelContextBytes = Buffer.concat([hexToBuf(channelId), hexToBuf(contractAddress)]);
    writeFileSync(join(FIXTURES_DIR, "channelContext.hex"), channelContextBytes.toString("hex") + "\n");
    console.log("   Written channelContext.hex");

    writeFileSync(join(FIXTURES_DIR, "validatorAddress.hex"), VALIDATOR_ADDRESS.slice(2) + "\n");
    console.log("   Written validatorAddress.hex");

    const metadata = {
      generatedAt: new Date().toISOString(),
      validatorAddress: VALIDATOR_ADDRESS,
      deployer: provisioned.DEPLOYER,
      contractAddress,
      qbftVerifier: verifierAddr,
      channelId,
      peerSigner: provisioned.PEER_SIGNER,
      codeHash: proof.codeHash,
      storageHash: proof.storageHash,
      proofBlockNumber: proofBlock,
      blockHash: block.hash,
      stateRoot: block.stateRoot,
      channelsSlot: CHANNELS_SLOT,
      provenStructOffsets: PROVEN_STRUCT_OFFSETS.map((o) => Number(o)),
      storageKeys,
      slotValues: proof.storageProof.map((sp) => sp.value),
      bundleContentHex: BUNDLE_CONTENT_BYTES.toString("hex"),
      accountProofNodes: proof.accountProof.length,
      storageProofEntries: proof.storageProof.length,
    };
    writeFileSync(join(FIXTURES_DIR, "metadata.json"), JSON.stringify(metadata, null, 2) + "\n");
    console.log("   Written metadata.json");

    writeFileSync(
      join(FIXTURES_DIR, "debug-proof-data.json"),
      JSON.stringify(
        {
          rawHeaderHex: headerRlp.toString("hex"),
          block: {
            hash: block.hash,
            stateRoot: block.stateRoot,
            number: block.number,
            extraData: block.extraData,
          },
          account: {
            nonce: proof.nonce,
            balance: proof.balance,
            storageHash: proof.storageHash,
            codeHash: proof.codeHash,
          },
          accountProof: proof.accountProof,
          storageProof: proof.storageProof.map((sp) => ({
            key: sp.key,
            value: sp.value,
            proof: sp.proof,
          })),
        },
        null,
        2
      ) + "\n"
    );
    console.log("   Written debug-proof-data.json");

    // 7b. Regenerate the FINAL configProof.hex with the real trust anchor and
    //     bundle header.  The bootstrap configProof written in step 1b has zeros
    //     for the trust anchor's service address and codeHash; those zeros would
    //     cause CodeHashMismatch when verifyBundle compares expectedCodeHash
    //     against the real contract's codeHash.  This step replaces the
    //     bootstrap file so generate-configproof.js no longer needs to be run
    //     separately.
    console.log("\n7b. Regenerating final configProof.hex...");
    const serviceAddress = Buffer.alloc(20, 0);
    const finalConfigProof = rlpEncode([
      hexToBuf(VALIDATOR_ADDRESS),                           // 0 validatorAddr
      serviceAddress,                                        // 1 serviceAddr (zeros — verifyConfig returns this as-is)
      Buffer.alloc(32, 0),                                   // 2 codeHash (zeros — not validated by verifyConfig)
      Buffer.from("eip155:1"),                               // 3 chainId
      Buffer.alloc(0),                                       // 4 peerConfigNanos (empty)
      BOOTSTRAP_THROTTLES.map((v) => hexToTrimmedBuf("0x" + v.toString(16))), // 5 throttles
      trustAnchorRlp,                                        // 6 trustAnchor (doubly-encoded: real service addr + codeHash)
      Buffer.alloc(0),                                       // 7 trustAnchorId (empty)
      rlpDecode(headerRlp),                                  // 8 blockHeader (from bundle block, spliced as a nested list)
      hexToTrimmedBuf("0x" + EPOCH_LENGTH.toString(16)),     // 9 epochLength
    ]);
    writeFileSync(join(FIXTURES_DIR, "configProof.hex"), finalConfigProof.toString("hex") + "\n");
    writeFileSync(join(FIXTURES_DIR, "serviceAddress.hex"), serviceAddress.toString("hex") + "\n");
    console.log(`   Written final configProof.hex (${finalConfigProof.length} bytes, replaces bootstrap)`);
    console.log("   Written serviceAddress.hex");

    console.log("\n=== Done! ===");
    console.log(`\nFixture directory: ${FIXTURES_DIR}`);
    console.log("  bundlePayload.hex      — RLP([header, epoch block headers, accountProof, storageProof, bundleContent])");
    console.log("  configProof.hex        — RLP([validator, serviceAddr, codeHash, chainId, nanos, throttles, trustAnchor, trustAnchorId, header, epochLength])");
    console.log("  trustAnchor.hex        — RLP([validatorAddr20, serviceAddr20, codeHash32]) — wire sub-list embedded in configProof.hex field 6");
    console.log("  channelContext.hex  — channelId32 || serviceAddr20 (ClprTypes.encodeChannelContext); pass as verifyBundle's 3rd arg");
    console.log("  validatorAddress.hex   — 20-byte validator address (raw)");
    console.log("  serviceAddress.hex     — 20-byte service address (raw)");
    console.log("  metadata.json          — channelId, derived keys, slot values, etc.");
    console.log("  debug-proof-data.json  — raw JSON-RPC dump for debugging");

  } finally {
    console.log("\n8. Stopping Besu cluster...");
    try { execSync("docker compose down -v", { cwd: __dirname, stdio: "pipe" }); } catch { }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Header reconstruction fallback (debug_getRawHeader unavailable)
// ─────────────────────────────────────────────────────────────────────────────

function buildHeaderRlpFromBlock(block) {
  const fields = [
    hexToBuf(block.parentHash),
    hexToBuf(block.sha3Uncles),
    hexToBuf(block.miner),
    hexToBuf(block.stateRoot),
    hexToBuf(block.transactionsRoot),
    hexToBuf(block.receiptsRoot),
    hexToBuf(block.logsBloom),
    hexToTrimmedBuf(block.difficulty),
    hexToTrimmedBuf(block.number),
    hexToTrimmedBuf(block.gasLimit),
    hexToTrimmedBuf(block.gasUsed),
    hexToTrimmedBuf(block.timestamp),
    hexToBuf(block.extraData),
    hexToBuf(block.mixHash),
    hexToBuf(block.nonce),
  ];
  if (block.baseFeePerGas != null) fields.push(hexToTrimmedBuf(block.baseFeePerGas));
  if (block.withdrawalsRoot != null) fields.push(hexToBuf(block.withdrawalsRoot));
  if (block.blobGasUsed != null) {
    fields.push(hexToTrimmedBuf(block.blobGasUsed));
    fields.push(hexToTrimmedBuf(block.excessBlobGas));
  }
  if (block.parentBeaconBlockRoot != null) fields.push(hexToBuf(block.parentBeaconBlockRoot));
  if (block.requestsHash != null) fields.push(hexToBuf(block.requestsHash));
  return rlpEncode(fields);
}

main().catch((err) => {
  console.error("\nFATAL:", err.message || err);
  try { execSync("docker compose down -v", { cwd: __dirname, stdio: "pipe" }); } catch {}
  process.exit(1);
});
