// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

import "forge-std/Test.sol";
import {ClprService} from "@hiero-ledger/clpr/ClprService.sol";
import {IClprService} from "@hiero-ledger/clpr/interfaces/IClprService.sol";
import {ClprTypes} from "@hiero-ledger/clpr/libraries/ClprTypes.sol";
import {ClprEvmStateProof} from "@hiero-ledger/clpr/libraries/proof/evm/ClprEvmStateProof.sol";
import {QBFTVerifier} from "@hiero-ledger/clpr/verifiers/evm/qbft/QBFTVerifier.sol";
import {IntegrationTestBase} from "@test/integration/IntegrationTestBase.sol";
import {QbftSyntheticProofs} from "@test/helpers/QbftSyntheticProofs.sol";
import {RLP} from "@openzeppelin/contracts/utils/RLP.sol";
import {Memory} from "@openzeppelin/contracts/utils/Memory.sol";

/// @dev Integration test exercising QBFT proof verification end-to-end.
///
/// Mirrors IntegrationMock's lifecycle as closely as possible:
///   _registerConnectorAndSend → submitBundle → _verifyPostBundle → _closeChannel
///
/// The fixture was generated by `tools/qbft-proof-generator/generate-fixture.js`
/// against a live Besu QBFT node using the same SIGNER_PK (0xC0DE) and connector
/// seed ("integration-connector") as the local test, so channel/connector IDs
/// match and msg1 delivers to the local MockClprConnector → MockClprApplication.
///
/// What differs from the mock test:
///   - The bundle has no peer REPLY (Besu can't emit field-2 payloads without a
///     real round-trip), so `expectedResponseCount = 0` and `expectedAckedMsgId = 0`.
///   - msg2 is a second DATA from a Besu-local connector; it doesn't deliver locally
///     but makes receivedMessageId = 2 and nextMessageId = 3 consistent with the mock.
contract IntegrationQBFTTest is IntegrationTestBase, QbftSyntheticProofs {
    // Anvil test account #0 — the validator address that signed the fixture config proof.
    uint256 internal constant QBFT_VALIDATOR_PK = 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80;

    /// @dev Selector of the builtin `Panic(uint256)` - solc's marker for unchecked indexing or
    ///      arithmetic, i.e. a missing guard rather than a deliberate rejection.
    bytes4 internal constant PANIC_SELECTOR = 0x4e487b71;

    QBFTVerifier internal qbftVerifier;

    string internal constant BUNDLE_PATH = "test/verifiers/evm/qbft/fixtures/bundlePayload.hex";
    string internal constant CONFIG_PROOF_PATH = "test/verifiers/evm/qbft/fixtures/configProof.hex";
    bytes internal bundlePayload;

    function setUp() public override {
        qbftVerifier = QBFTVerifier(deployCode("QBFTVerifier.sol:QBFTVerifier", abi.encode(uint8(2))));
        bundlePayload = _readHexFile(BUNDLE_PATH);
        _deployServiceAndConnect(address(qbftVerifier));
    }

    function _deployAndConnectVerifier(address verifier_) internal override {
        bytes memory pubKey = _signerPubKey();
        channelId = _deriveTestChannelId(pubKey, bytes32(0));
        bytes32 commitment = keccak256(abi.encodePacked(channelId, pubKey));
        service.registerChannel(channelId, commitment);

        bytes32 msgHash = keccak256(abi.encodePacked(channelId, address(service)));
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(SIGNER_PK, _ethSignedHash(msgHash));
        bytes memory configProof = _readHexFile(CONFIG_PROOF_PATH);
        service.completeChannel(channelId, pubKey, abi.encodePacked(r, s, v), bytes32(0), verifier_, configProof, "");
    }

    // ═══════════════════════════════════════════════════════════════════
    // Full lifecycle: register connector → send → receive bundle → close
    // ═══════════════════════════════════════════════════════════════════
    /// @dev Requires fresh fixture: `node tools/qbft-proof-generator/generate-fixture.js`
    ///      bundlePayload.hex must be rebuilt with the 5-item layout:
    ///      [currentHeader, epochHeaders[], accountProof, storageProof, bundleContent]
    function test_fullLifecycle() public {
        Memory.Slice[] memory topLevel = RLP.decodeList(bundlePayload);
        if (topLevel.length != 5) {
            vm.skip(true); // stale fixture — regenerate with node generate-fixture.js
        }
        Memory.Slice[] memory storageEntries = RLP.readList(topLevel[3]);
        if (storageEntries.length != 4 && storageEntries.length != 5) {
            vm.skip(true); // old storage proof format — channelId now lives in ChannelContext
        }

        uint64 outboundMsgId = _registerConnectorAndSend();
        assertEq(outboundMsgId, 1, "first outbound message");

        service.submitBundle(channelId, bundlePayload);

        _verifyPostBundle(1, 3, hex"48454C4C4F", 2, 1, 0, ClprTypes.ChannelStatus.ACTIVE, 0);
        _closeChannel();
    }

    // ═══════════════════════════════════════════════════════════════════
    // Cross-channel isolation
    // ═══════════════════════════════════════════════════════════════════
    // A proof whose storage entries are keyed to a different channelId must be
    // rejected even if the header seal and account proof are valid. The verifier
    // derives slot keys from the channelId stored in its ChannelContext and enforces
    // that the submitted proof covers exactly those slots.
    function test_rejectBundle_storageProofForWrongChannel() public override {
        ClprTypes.Channel memory channel = service.getChannel(channelId);
        (, bytes32 codeHash, uint64 epochLength, uint64 epochNumber) =
            abi.decode(channel.trustAnchor, (address, bytes32, uint64, uint64));
        ClprTypes.ChannelContext memory ctx = ClprTypes.decodeChannelContext(channel.channelContext);
        address clprService;
        bytes memory svc = ctx.remoteServiceAddress;
        assembly {
            clprService := mload(add(svc, 20))
        }

        bytes32 wrongConnId = bytes32(uint256(0xBADC0DE));

        (bytes32 storageRoot, bytes memory storageProofRlp) = _buildChannelStorageProof(wrongConnId);
        (bytes32 stateRoot, bytes memory accountProofRlp) =
            _buildSyntheticAccountProof(clprService, storageRoot, codeHash);

        // Header must be in the same epoch as the trust anchor so the verifier
        // reaches the storage proof check rather than reverting on EpochMismatch.
        uint256 blockNumber = uint256(epochNumber) * uint256(epochLength) + 1;
        // QBFTVerifier(2) requires MIN_COMMITTED_SEALS = 2: sign with the fixture
        // validator (QBFT_VALIDATOR_PK) plus one extra key.
        uint256 extraSignerPk = uint256(keccak256("extra-signer"));
        bytes memory header =
            _buildMultiSealedHeaderAtBlock(blockNumber, stateRoot, 0, QBFT_VALIDATOR_PK, extraSignerPk);

        bytes[] memory top = new bytes[](5);
        top[0] = header;
        top[1] = hex"c0";
        top[2] = accountProofRlp;
        top[3] = storageProofRlp;
        top[4] = RLP.encode(new bytes(0));

        bytes32 expectedMissingSlot = bytes32(uint256(keccak256(abi.encode(channelId, uint256(15)))) + 1);
        vm.expectRevert(abi.encodeWithSelector(ClprEvmStateProof.SlotNotProven.selector, expectedMissingSlot));
        service.submitBundle(channelId, RLP.encode(top));
    }

    // ═══════════════════════════════════════════════════════════════════
    // Malformed proof through the permissionless entry point
    // ═══════════════════════════════════════════════════════════════════
    /// @dev `submitBundle` is permissionless, so any caller can hand it arbitrary bytes. A structurally
    ///      corrupt proof must be rejected with a named error rather than a `Panic`, and must leave the
    ///      channel exactly as it found it.
    ///
    ///      0xb8 is chosen deliberately: it is the RLP long-string prefix, the shortest input that
    ///      reaches the length-prefix decode path where the guard used to run after the read rather
    ///      than before it.
    function test_rejectBundle_singleByteProof_namedErrorAndNoStateChange() public {
        ClprTypes.Channel memory before = service.getChannel(channelId);
        uint256 messageCallsBefore = app.getMessageCallCount();
        uint256 responseCallsBefore = app.getResponseCallCount();

        (bool ok, bytes memory returndata) =
            address(service).call(abi.encodeCall(IClprService.submitBundle, (channelId, hex"b8")));

        assertFalse(ok, "submitBundle must reject a one-byte proof");
        assertGe(returndata.length, 4, "revert must carry an error selector, not empty returndata");
        // casting to 'bytes4' is safe because it is the intended selector read: the length assertion
        // above ensures 4 bytes are present, and dropping the trailing arguments is what reading a
        // selector means.
        // forge-lint: disable-next-line(unsafe-typecast)
        assertTrue(bytes4(returndata) != PANIC_SELECTOR, "submitBundle reverted with Panic instead of a named error");

        ClprTypes.Channel memory afterCall = service.getChannel(channelId);
        assertEq(afterCall.nextMessageId, before.nextMessageId, "nextMessageId must be unchanged");
        assertEq(afterCall.receivedMessageId, before.receivedMessageId, "receivedMessageId must be unchanged");
        assertEq(afterCall.ackedMessageId, before.ackedMessageId, "ackedMessageId must be unchanged");
        assertEq(afterCall.nextExpectedReplyId, before.nextExpectedReplyId, "nextExpectedReplyId must be unchanged");
        assertEq(uint8(afterCall.status), uint8(before.status), "channel status must be unchanged");
        assertEq(afterCall.receivedRunningHash, before.receivedRunningHash, "receivedRunningHash must be unchanged");
        assertEq(afterCall.sentRunningHash, before.sentRunningHash, "sentRunningHash must be unchanged");
        assertEq(app.getMessageCallCount(), messageCallsBefore, "no message may be delivered");
        assertEq(app.getResponseCallCount(), responseCallsBefore, "no response callback may fire");
    }

    function _readHexFile(string memory path) internal view returns (bytes memory) {
        string memory raw = vm.readFile(path);
        bytes memory b = bytes(raw);
        while (b.length > 0 && (b[b.length - 1] == 0x0a || b[b.length - 1] == 0x0d)) {
            assembly {
                mstore(b, sub(mload(b), 1))
            }
        }
        return vm.parseBytes(string.concat("0x", string(b)));
    }
}
